spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      server:
        webflux:
          routes:
            - id: a-service
              uri: lb://a-service
              predicates:
              - Path=/a/**
              filters:
              - StripPrefix=1

            - id: b-service
              uri: lb://b-service
              predicates:
              - Path=/b/**
              filters:
              - StripPrefix=1

  config:
    import:
      # 动态引入 Nacos Config 配置
      # Data ID: gateway-logging.yaml
      # Group:   LOG_GROUP
      # 由于配置内容在 Nacos Config 中，git无法直接跟踪
      # 所以将配置用注释记录在这里
      # 该配置原用于临时开启gateway项目的DEBUG日志：
      # -------------------------------------------
      # logging:
      #   level:
      #     org.springframework.cloud.gateway: DEBUG
      # -------------------------------------------
      - nacos:gateway-logging.yaml?group=LOG_GROUP&refreshEnabled=true