spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      server:
        webflux:
          routes:
            - id: a-service
              uri: lb://a-service
              predicates:
              - Path=/a/**
              filters:
              - StripPrefix=1

            - id: b-service
              uri: lb://b-service
              predicates:
              - Path=/b/**
              filters:
              - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG